# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chkbal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
