# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chkbal', '0002_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='IFSC_Code',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accountno',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
