# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chkbal', '0003_auto_20170308_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('accountno', models.CharField(default='', max_length=16)),
                ('IFSC_Code', models.CharField(default='', max_length=16)),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='unknown', max_length=100)),
                ('phone', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
