# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chkbal', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='IFSC_Code',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountno',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
