# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chkbal', '0006_auto_20170319_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.CharField(default=500, max_length=100),
        ),
    ]
