# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chkbal', '0007_auto_20170319_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Mp',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
